spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abel
    url: jdbc:mysql://[2a02:8308:6005:af00:c91:b78b:85fd:9a6e]:3306/cursos?serverTimezone=UTC
    password: kkabel
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    service-url:
      defaultZone: http://[2a02:8308:6005:af00:c91:b78b:85fd:9a6e]:8761/eureka
  instance:
    instance-id: instancia2
server:
  port: '8082'
