spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: abel
    url: jdbc:mysql://192.168.0.179:3306/cursos?serverTimezone=UTC
    password: kkabel
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.179:8761/eureka
  instance:
    hostname: 192.168.0.6
server:
  port: '8500'
